#! /usr/bin/env python3
#

import cProfile, pstats, io
from pstats import SortKey

from lieer import Gmailieer

if __name__ == '__main__':
  g = Gmailieer ()

  pr = cProfile.Profile()
  pr.enable ()

  g.main ()

  pr.disable ()

  s = io.StringIO ()
  ps = pstats.Stats (pr, stream = s).sort_stats (SortKey.CUMULATIVE)
  ps.print_stats ()
  print (s.getvalue ())

